// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: campaigns.sql

package statedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCampaign = `-- name: CreateCampaign :one
INSERT INTO campaigns (
  name,
  description,
  genre,
  tone,
  themes,
  status,
  created_by
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7
)
RETURNING id, name, description, genre, tone, themes, status, created_by, created_at, updated_at
`

type CreateCampaignParams struct {
	Name        string
	Description pgtype.Text
	Genre       pgtype.Text
	Tone        pgtype.Text
	Themes      []string
	Status      string
	CreatedBy   pgtype.UUID
}

func (q *Queries) CreateCampaign(ctx context.Context, arg CreateCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, createCampaign,
		arg.Name,
		arg.Description,
		arg.Genre,
		arg.Tone,
		arg.Themes,
		arg.Status,
		arg.CreatedBy,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Genre,
		&i.Tone,
		&i.Themes,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCampaign = `-- name: DeleteCampaign :exec
DELETE FROM campaigns
WHERE id = $1
`

func (q *Queries) DeleteCampaign(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCampaign, id)
	return err
}

const getCampaignByID = `-- name: GetCampaignByID :one
SELECT id, name, description, genre, tone, themes, status, created_by, created_at, updated_at
FROM campaigns
WHERE id = $1
`

func (q *Queries) GetCampaignByID(ctx context.Context, id pgtype.UUID) (Campaign, error) {
	row := q.db.QueryRow(ctx, getCampaignByID, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Genre,
		&i.Tone,
		&i.Themes,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCampaignsByUser = `-- name: ListCampaignsByUser :many
SELECT id, name, description, genre, tone, themes, status, created_by, created_at, updated_at
FROM campaigns
WHERE created_by = $1
ORDER BY created_at, id
`

func (q *Queries) ListCampaignsByUser(ctx context.Context, createdBy pgtype.UUID) ([]Campaign, error) {
	rows, err := q.db.Query(ctx, listCampaignsByUser, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Campaign
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Genre,
			&i.Tone,
			&i.Themes,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCampaign = `-- name: UpdateCampaign :one
UPDATE campaigns
SET
  name = $2,
  description = $3,
  genre = $4,
  tone = $5,
  themes = $6,
  updated_at = now()
WHERE id = $1
RETURNING id, name, description, genre, tone, themes, status, created_by, created_at, updated_at
`

type UpdateCampaignParams struct {
	ID          pgtype.UUID
	Name        string
	Description pgtype.Text
	Genre       pgtype.Text
	Tone        pgtype.Text
	Themes      []string
}

func (q *Queries) UpdateCampaign(ctx context.Context, arg UpdateCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, updateCampaign,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Genre,
		arg.Tone,
		arg.Themes,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Genre,
		&i.Tone,
		&i.Themes,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCampaignStatus = `-- name: UpdateCampaignStatus :one
UPDATE campaigns
SET
  status = $2,
  updated_at = now()
WHERE id = $1
RETURNING id, name, description, genre, tone, themes, status, created_by, created_at, updated_at
`

type UpdateCampaignStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) UpdateCampaignStatus(ctx context.Context, arg UpdateCampaignStatusParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, updateCampaignStatus, arg.ID, arg.Status)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Genre,
		&i.Tone,
		&i.Themes,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
