// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: entity_relationships.sql

package statedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRelationship = `-- name: CreateRelationship :one
INSERT INTO entity_relationships (
  campaign_id,
  source_entity_type,
  source_entity_id,
  target_entity_type,
  target_entity_id,
  relationship_type,
  description,
  strength
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8
)
RETURNING id, campaign_id, source_entity_type, source_entity_id, target_entity_type, target_entity_id, relationship_type, description, strength, created_at, updated_at
`

type CreateRelationshipParams struct {
	CampaignID       pgtype.UUID
	SourceEntityType string
	SourceEntityID   pgtype.UUID
	TargetEntityType string
	TargetEntityID   pgtype.UUID
	RelationshipType string
	Description      pgtype.Text
	Strength         pgtype.Int4
}

func (q *Queries) CreateRelationship(ctx context.Context, arg CreateRelationshipParams) (EntityRelationship, error) {
	row := q.db.QueryRow(ctx, createRelationship,
		arg.CampaignID,
		arg.SourceEntityType,
		arg.SourceEntityID,
		arg.TargetEntityType,
		arg.TargetEntityID,
		arg.RelationshipType,
		arg.Description,
		arg.Strength,
	)
	var i EntityRelationship
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.SourceEntityType,
		&i.SourceEntityID,
		&i.TargetEntityType,
		&i.TargetEntityID,
		&i.RelationshipType,
		&i.Description,
		&i.Strength,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRelationship = `-- name: DeleteRelationship :exec
DELETE FROM entity_relationships
WHERE id = $1
  AND campaign_id = $2
`

type DeleteRelationshipParams struct {
	ID         pgtype.UUID
	CampaignID pgtype.UUID
}

func (q *Queries) DeleteRelationship(ctx context.Context, arg DeleteRelationshipParams) error {
	_, err := q.db.Exec(ctx, deleteRelationship, arg.ID, arg.CampaignID)
	return err
}

const getRelationshipsBetween = `-- name: GetRelationshipsBetween :many
SELECT id, campaign_id, source_entity_type, source_entity_id, target_entity_type, target_entity_id, relationship_type, description, strength, created_at, updated_at
FROM entity_relationships
WHERE campaign_id = $1
  AND (
    (
      source_entity_type = $2
      AND source_entity_id = $3
      AND target_entity_type = $4
      AND target_entity_id = $5
    )
    OR
    (
      source_entity_type = $4
      AND source_entity_id = $5
      AND target_entity_type = $2
      AND target_entity_id = $3
    )
  )
ORDER BY created_at, id
`

type GetRelationshipsBetweenParams struct {
	CampaignID       pgtype.UUID
	FirstEntityType  string
	FirstEntityID    pgtype.UUID
	SecondEntityType string
	SecondEntityID   pgtype.UUID
}

func (q *Queries) GetRelationshipsBetween(ctx context.Context, arg GetRelationshipsBetweenParams) ([]EntityRelationship, error) {
	rows, err := q.db.Query(ctx, getRelationshipsBetween,
		arg.CampaignID,
		arg.FirstEntityType,
		arg.FirstEntityID,
		arg.SecondEntityType,
		arg.SecondEntityID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntityRelationship
	for rows.Next() {
		var i EntityRelationship
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.SourceEntityType,
			&i.SourceEntityID,
			&i.TargetEntityType,
			&i.TargetEntityID,
			&i.RelationshipType,
			&i.Description,
			&i.Strength,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRelationshipsByEntity = `-- name: GetRelationshipsByEntity :many
SELECT id, campaign_id, source_entity_type, source_entity_id, target_entity_type, target_entity_id, relationship_type, description, strength, created_at, updated_at
FROM entity_relationships
WHERE campaign_id = $1
  AND (
    (source_entity_type = $2 AND source_entity_id = $3)
    OR
    (target_entity_type = $2 AND target_entity_id = $3)
  )
ORDER BY created_at, id
`

type GetRelationshipsByEntityParams struct {
	CampaignID pgtype.UUID
	EntityType string
	EntityID   pgtype.UUID
}

func (q *Queries) GetRelationshipsByEntity(ctx context.Context, arg GetRelationshipsByEntityParams) ([]EntityRelationship, error) {
	rows, err := q.db.Query(ctx, getRelationshipsByEntity, arg.CampaignID, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntityRelationship
	for rows.Next() {
		var i EntityRelationship
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.SourceEntityType,
			&i.SourceEntityID,
			&i.TargetEntityType,
			&i.TargetEntityID,
			&i.RelationshipType,
			&i.Description,
			&i.Strength,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelationshipsByCampaign = `-- name: ListRelationshipsByCampaign :many
SELECT id, campaign_id, source_entity_type, source_entity_id, target_entity_type, target_entity_id, relationship_type, description, strength, created_at, updated_at
FROM entity_relationships
WHERE campaign_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListRelationshipsByCampaign(ctx context.Context, campaignID pgtype.UUID) ([]EntityRelationship, error) {
	rows, err := q.db.Query(ctx, listRelationshipsByCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntityRelationship
	for rows.Next() {
		var i EntityRelationship
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.SourceEntityType,
			&i.SourceEntityID,
			&i.TargetEntityType,
			&i.TargetEntityID,
			&i.RelationshipType,
			&i.Description,
			&i.Strength,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRelationship = `-- name: UpdateRelationship :one
UPDATE entity_relationships
SET
  relationship_type = $1,
  description = $2,
  strength = $3,
  updated_at = now()
WHERE id = $4
  AND campaign_id = $5
RETURNING id, campaign_id, source_entity_type, source_entity_id, target_entity_type, target_entity_id, relationship_type, description, strength, created_at, updated_at
`

type UpdateRelationshipParams struct {
	RelationshipType string
	Description      pgtype.Text
	Strength         pgtype.Int4
	ID               pgtype.UUID
	CampaignID       pgtype.UUID
}

func (q *Queries) UpdateRelationship(ctx context.Context, arg UpdateRelationshipParams) (EntityRelationship, error) {
	row := q.db.QueryRow(ctx, updateRelationship,
		arg.RelationshipType,
		arg.Description,
		arg.Strength,
		arg.ID,
		arg.CampaignID,
	)
	var i EntityRelationship
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.SourceEntityType,
		&i.SourceEntityID,
		&i.TargetEntityType,
		&i.TargetEntityID,
		&i.RelationshipType,
		&i.Description,
		&i.Strength,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
