// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: expanded_world.sql

package statedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBeliefSystem = `-- name: CreateBeliefSystem :one
INSERT INTO belief_systems (
  campaign_id,
  name,
  details
) VALUES (
  $1,
  $2,
  COALESCE($3::jsonb, '{}'::jsonb)
)
RETURNING id, campaign_id, name, details, created_at, updated_at
`

type CreateBeliefSystemParams struct {
	CampaignID pgtype.UUID
	Name       string
	Details    []byte
}

func (q *Queries) CreateBeliefSystem(ctx context.Context, arg CreateBeliefSystemParams) (BeliefSystem, error) {
	row := q.db.QueryRow(ctx, createBeliefSystem, arg.CampaignID, arg.Name, arg.Details)
	var i BeliefSystem
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Details,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCulture = `-- name: CreateCulture :one
INSERT INTO cultures (
  campaign_id,
  language_id,
  belief_system_id,
  name,
  details
) VALUES (
  $1,
  $2,
  $3,
  $4,
  COALESCE($5::jsonb, '{}'::jsonb)
)
RETURNING id, campaign_id, language_id, belief_system_id, name, details, created_at, updated_at
`

type CreateCultureParams struct {
	CampaignID     pgtype.UUID
	LanguageID     pgtype.UUID
	BeliefSystemID pgtype.UUID
	Name           string
	Details        []byte
}

func (q *Queries) CreateCulture(ctx context.Context, arg CreateCultureParams) (Culture, error) {
	row := q.db.QueryRow(ctx, createCulture,
		arg.CampaignID,
		arg.LanguageID,
		arg.BeliefSystemID,
		arg.Name,
		arg.Details,
	)
	var i Culture
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.LanguageID,
		&i.BeliefSystemID,
		&i.Name,
		&i.Details,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEconomicSystem = `-- name: CreateEconomicSystem :one
INSERT INTO economic_systems (
  campaign_id,
  name,
  details
) VALUES (
  $1,
  $2,
  COALESCE($3::jsonb, '{}'::jsonb)
)
RETURNING id, campaign_id, name, details, created_at, updated_at
`

type CreateEconomicSystemParams struct {
	CampaignID pgtype.UUID
	Name       string
	Details    []byte
}

func (q *Queries) CreateEconomicSystem(ctx context.Context, arg CreateEconomicSystemParams) (EconomicSystem, error) {
	row := q.db.QueryRow(ctx, createEconomicSystem, arg.CampaignID, arg.Name, arg.Details)
	var i EconomicSystem
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Details,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLanguage = `-- name: CreateLanguage :one
INSERT INTO languages (
  campaign_id,
  name,
  phonology,
  naming,
  vocabulary
) VALUES (
  $1,
  $2,
  COALESCE($3::jsonb, '{}'::jsonb),
  COALESCE($4::jsonb, '{}'::jsonb),
  COALESCE($5::jsonb, '{}'::jsonb)
)
RETURNING id, campaign_id, name, phonology, naming, vocabulary, created_at, updated_at
`

type CreateLanguageParams struct {
	CampaignID pgtype.UUID
	Name       string
	Phonology  []byte
	Naming     []byte
	Vocabulary []byte
}

func (q *Queries) CreateLanguage(ctx context.Context, arg CreateLanguageParams) (Language, error) {
	row := q.db.QueryRow(ctx, createLanguage,
		arg.CampaignID,
		arg.Name,
		arg.Phonology,
		arg.Naming,
		arg.Vocabulary,
	)
	var i Language
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Phonology,
		&i.Naming,
		&i.Vocabulary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBeliefSystem = `-- name: DeleteBeliefSystem :exec
DELETE FROM belief_systems
WHERE id = $1
`

func (q *Queries) DeleteBeliefSystem(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBeliefSystem, id)
	return err
}

const deleteCulture = `-- name: DeleteCulture :exec
DELETE FROM cultures
WHERE id = $1
`

func (q *Queries) DeleteCulture(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCulture, id)
	return err
}

const deleteEconomicSystem = `-- name: DeleteEconomicSystem :exec
DELETE FROM economic_systems
WHERE id = $1
`

func (q *Queries) DeleteEconomicSystem(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEconomicSystem, id)
	return err
}

const deleteLanguage = `-- name: DeleteLanguage :exec
DELETE FROM languages
WHERE id = $1
`

func (q *Queries) DeleteLanguage(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteLanguage, id)
	return err
}

const getBeliefSystemByCulture = `-- name: GetBeliefSystemByCulture :one
SELECT b.id, b.campaign_id, b.name, b.details, b.created_at, b.updated_at
FROM belief_systems b
INNER JOIN cultures c
  ON c.belief_system_id = b.id
WHERE c.id = $1
`

func (q *Queries) GetBeliefSystemByCulture(ctx context.Context, cultureID pgtype.UUID) (BeliefSystem, error) {
	row := q.db.QueryRow(ctx, getBeliefSystemByCulture, cultureID)
	var i BeliefSystem
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Details,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBeliefSystemByID = `-- name: GetBeliefSystemByID :one
SELECT id, campaign_id, name, details, created_at, updated_at
FROM belief_systems
WHERE id = $1
`

func (q *Queries) GetBeliefSystemByID(ctx context.Context, id pgtype.UUID) (BeliefSystem, error) {
	row := q.db.QueryRow(ctx, getBeliefSystemByID, id)
	var i BeliefSystem
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Details,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCultureByID = `-- name: GetCultureByID :one
SELECT id, campaign_id, language_id, belief_system_id, name, details, created_at, updated_at
FROM cultures
WHERE id = $1
`

func (q *Queries) GetCultureByID(ctx context.Context, id pgtype.UUID) (Culture, error) {
	row := q.db.QueryRow(ctx, getCultureByID, id)
	var i Culture
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.LanguageID,
		&i.BeliefSystemID,
		&i.Name,
		&i.Details,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEconomicSystemByID = `-- name: GetEconomicSystemByID :one
SELECT id, campaign_id, name, details, created_at, updated_at
FROM economic_systems
WHERE id = $1
`

func (q *Queries) GetEconomicSystemByID(ctx context.Context, id pgtype.UUID) (EconomicSystem, error) {
	row := q.db.QueryRow(ctx, getEconomicSystemByID, id)
	var i EconomicSystem
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Details,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLanguageByID = `-- name: GetLanguageByID :one
SELECT id, campaign_id, name, phonology, naming, vocabulary, created_at, updated_at
FROM languages
WHERE id = $1
`

func (q *Queries) GetLanguageByID(ctx context.Context, id pgtype.UUID) (Language, error) {
	row := q.db.QueryRow(ctx, getLanguageByID, id)
	var i Language
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Phonology,
		&i.Naming,
		&i.Vocabulary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBeliefSystemsByCampaign = `-- name: ListBeliefSystemsByCampaign :many
SELECT id, campaign_id, name, details, created_at, updated_at
FROM belief_systems
WHERE campaign_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListBeliefSystemsByCampaign(ctx context.Context, campaignID pgtype.UUID) ([]BeliefSystem, error) {
	rows, err := q.db.Query(ctx, listBeliefSystemsByCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BeliefSystem
	for rows.Next() {
		var i BeliefSystem
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Name,
			&i.Details,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCulturesByCampaign = `-- name: ListCulturesByCampaign :many
SELECT id, campaign_id, language_id, belief_system_id, name, details, created_at, updated_at
FROM cultures
WHERE campaign_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListCulturesByCampaign(ctx context.Context, campaignID pgtype.UUID) ([]Culture, error) {
	rows, err := q.db.Query(ctx, listCulturesByCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Culture
	for rows.Next() {
		var i Culture
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.LanguageID,
			&i.BeliefSystemID,
			&i.Name,
			&i.Details,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCulturesByLanguage = `-- name: ListCulturesByLanguage :many
SELECT id, campaign_id, language_id, belief_system_id, name, details, created_at, updated_at
FROM cultures
WHERE language_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListCulturesByLanguage(ctx context.Context, languageID pgtype.UUID) ([]Culture, error) {
	rows, err := q.db.Query(ctx, listCulturesByLanguage, languageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Culture
	for rows.Next() {
		var i Culture
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.LanguageID,
			&i.BeliefSystemID,
			&i.Name,
			&i.Details,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEconomicSystemsByCampaign = `-- name: ListEconomicSystemsByCampaign :many
SELECT id, campaign_id, name, details, created_at, updated_at
FROM economic_systems
WHERE campaign_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListEconomicSystemsByCampaign(ctx context.Context, campaignID pgtype.UUID) ([]EconomicSystem, error) {
	rows, err := q.db.Query(ctx, listEconomicSystemsByCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EconomicSystem
	for rows.Next() {
		var i EconomicSystem
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Name,
			&i.Details,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLanguagesByCampaign = `-- name: ListLanguagesByCampaign :many
SELECT id, campaign_id, name, phonology, naming, vocabulary, created_at, updated_at
FROM languages
WHERE campaign_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListLanguagesByCampaign(ctx context.Context, campaignID pgtype.UUID) ([]Language, error) {
	rows, err := q.db.Query(ctx, listLanguagesByCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Language
	for rows.Next() {
		var i Language
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Name,
			&i.Phonology,
			&i.Naming,
			&i.Vocabulary,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLanguagesByFaction = `-- name: ListLanguagesByFaction :many
SELECT l.id, l.campaign_id, l.name, l.phonology, l.naming, l.vocabulary, l.created_at, l.updated_at
FROM languages l
INNER JOIN factions f
  ON f.campaign_id = l.campaign_id
WHERE f.id = $1
ORDER BY l.created_at, l.id
`

func (q *Queries) ListLanguagesByFaction(ctx context.Context, factionID pgtype.UUID) ([]Language, error) {
	rows, err := q.db.Query(ctx, listLanguagesByFaction, factionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Language
	for rows.Next() {
		var i Language
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Name,
			&i.Phonology,
			&i.Naming,
			&i.Vocabulary,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBeliefSystem = `-- name: UpdateBeliefSystem :one
UPDATE belief_systems
SET
  name = $1,
  details = COALESCE($2::jsonb, details),
  updated_at = now()
WHERE id = $3
RETURNING id, campaign_id, name, details, created_at, updated_at
`

type UpdateBeliefSystemParams struct {
	Name    string
	Details []byte
	ID      pgtype.UUID
}

func (q *Queries) UpdateBeliefSystem(ctx context.Context, arg UpdateBeliefSystemParams) (BeliefSystem, error) {
	row := q.db.QueryRow(ctx, updateBeliefSystem, arg.Name, arg.Details, arg.ID)
	var i BeliefSystem
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Details,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCulture = `-- name: UpdateCulture :one
UPDATE cultures
SET
  language_id = $1,
  belief_system_id = $2,
  name = $3,
  details = COALESCE($4::jsonb, details),
  updated_at = now()
WHERE id = $5
RETURNING id, campaign_id, language_id, belief_system_id, name, details, created_at, updated_at
`

type UpdateCultureParams struct {
	LanguageID     pgtype.UUID
	BeliefSystemID pgtype.UUID
	Name           string
	Details        []byte
	ID             pgtype.UUID
}

func (q *Queries) UpdateCulture(ctx context.Context, arg UpdateCultureParams) (Culture, error) {
	row := q.db.QueryRow(ctx, updateCulture,
		arg.LanguageID,
		arg.BeliefSystemID,
		arg.Name,
		arg.Details,
		arg.ID,
	)
	var i Culture
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.LanguageID,
		&i.BeliefSystemID,
		&i.Name,
		&i.Details,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEconomicSystem = `-- name: UpdateEconomicSystem :one
UPDATE economic_systems
SET
  name = $1,
  details = COALESCE($2::jsonb, details),
  updated_at = now()
WHERE id = $3
RETURNING id, campaign_id, name, details, created_at, updated_at
`

type UpdateEconomicSystemParams struct {
	Name    string
	Details []byte
	ID      pgtype.UUID
}

func (q *Queries) UpdateEconomicSystem(ctx context.Context, arg UpdateEconomicSystemParams) (EconomicSystem, error) {
	row := q.db.QueryRow(ctx, updateEconomicSystem, arg.Name, arg.Details, arg.ID)
	var i EconomicSystem
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Details,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLanguage = `-- name: UpdateLanguage :one
UPDATE languages
SET
  name = $1,
  phonology = COALESCE($2::jsonb, phonology),
  naming = COALESCE($3::jsonb, naming),
  vocabulary = COALESCE($4::jsonb, vocabulary),
  updated_at = now()
WHERE id = $5
RETURNING id, campaign_id, name, phonology, naming, vocabulary, created_at, updated_at
`

type UpdateLanguageParams struct {
	Name       string
	Phonology  []byte
	Naming     []byte
	Vocabulary []byte
	ID         pgtype.UUID
}

func (q *Queries) UpdateLanguage(ctx context.Context, arg UpdateLanguageParams) (Language, error) {
	row := q.db.QueryRow(ctx, updateLanguage,
		arg.Name,
		arg.Phonology,
		arg.Naming,
		arg.Vocabulary,
		arg.ID,
	)
	var i Language
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Phonology,
		&i.Naming,
		&i.Vocabulary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
