// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: factions.sql

package statedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFaction = `-- name: CreateFaction :one
INSERT INTO factions (
  campaign_id,
  name,
  description,
  agenda,
  territory,
  properties
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  COALESCE($6::jsonb, '{}'::jsonb)
)
RETURNING id, campaign_id, name, description, agenda, territory, properties, created_at, updated_at
`

type CreateFactionParams struct {
	CampaignID  pgtype.UUID
	Name        string
	Description pgtype.Text
	Agenda      pgtype.Text
	Territory   pgtype.Text
	Properties  []byte
}

func (q *Queries) CreateFaction(ctx context.Context, arg CreateFactionParams) (Faction, error) {
	row := q.db.QueryRow(ctx, createFaction,
		arg.CampaignID,
		arg.Name,
		arg.Description,
		arg.Agenda,
		arg.Territory,
		arg.Properties,
	)
	var i Faction
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Description,
		&i.Agenda,
		&i.Territory,
		&i.Properties,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFactionRelationship = `-- name: CreateFactionRelationship :one
INSERT INTO faction_relationships (
  faction_id,
  related_faction_id,
  relationship_type,
  description
) VALUES (
  $1,
  $2,
  $3,
  $4
)
RETURNING id, faction_id, related_faction_id, relationship_type, description, created_at, updated_at
`

type CreateFactionRelationshipParams struct {
	FactionID        pgtype.UUID
	RelatedFactionID pgtype.UUID
	RelationshipType string
	Description      pgtype.Text
}

func (q *Queries) CreateFactionRelationship(ctx context.Context, arg CreateFactionRelationshipParams) (FactionRelationship, error) {
	row := q.db.QueryRow(ctx, createFactionRelationship,
		arg.FactionID,
		arg.RelatedFactionID,
		arg.RelationshipType,
		arg.Description,
	)
	var i FactionRelationship
	err := row.Scan(
		&i.ID,
		&i.FactionID,
		&i.RelatedFactionID,
		&i.RelationshipType,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFactionByID = `-- name: GetFactionByID :one
SELECT id, campaign_id, name, description, agenda, territory, properties, created_at, updated_at
FROM factions
WHERE id = $1
`

func (q *Queries) GetFactionByID(ctx context.Context, id pgtype.UUID) (Faction, error) {
	row := q.db.QueryRow(ctx, getFactionByID, id)
	var i Faction
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Description,
		&i.Agenda,
		&i.Territory,
		&i.Properties,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFactionRelationships = `-- name: GetFactionRelationships :many
SELECT id, faction_id, related_faction_id, relationship_type, description, created_at, updated_at
FROM faction_relationships
WHERE faction_id = $1
   OR related_faction_id = $1
ORDER BY created_at, id
`

func (q *Queries) GetFactionRelationships(ctx context.Context, factionID pgtype.UUID) ([]FactionRelationship, error) {
	rows, err := q.db.Query(ctx, getFactionRelationships, factionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FactionRelationship
	for rows.Next() {
		var i FactionRelationship
		if err := rows.Scan(
			&i.ID,
			&i.FactionID,
			&i.RelatedFactionID,
			&i.RelationshipType,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFactionsByCampaign = `-- name: ListFactionsByCampaign :many
SELECT id, campaign_id, name, description, agenda, territory, properties, created_at, updated_at
FROM factions
WHERE campaign_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListFactionsByCampaign(ctx context.Context, campaignID pgtype.UUID) ([]Faction, error) {
	rows, err := q.db.Query(ctx, listFactionsByCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Faction
	for rows.Next() {
		var i Faction
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Name,
			&i.Description,
			&i.Agenda,
			&i.Territory,
			&i.Properties,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFaction = `-- name: UpdateFaction :one
UPDATE factions
SET
  name = $1,
  description = $2,
  agenda = $3,
  territory = $4,
  properties = COALESCE($5::jsonb, properties),
  updated_at = now()
WHERE id = $6
RETURNING id, campaign_id, name, description, agenda, territory, properties, created_at, updated_at
`

type UpdateFactionParams struct {
	Name        string
	Description pgtype.Text
	Agenda      pgtype.Text
	Territory   pgtype.Text
	Properties  []byte
	ID          pgtype.UUID
}

func (q *Queries) UpdateFaction(ctx context.Context, arg UpdateFactionParams) (Faction, error) {
	row := q.db.QueryRow(ctx, updateFaction,
		arg.Name,
		arg.Description,
		arg.Agenda,
		arg.Territory,
		arg.Properties,
		arg.ID,
	)
	var i Faction
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Description,
		&i.Agenda,
		&i.Territory,
		&i.Properties,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFactionRelationship = `-- name: UpdateFactionRelationship :one
UPDATE faction_relationships
SET
  relationship_type = $1,
  description = $2,
  updated_at = now()
WHERE id = $3
RETURNING id, faction_id, related_faction_id, relationship_type, description, created_at, updated_at
`

type UpdateFactionRelationshipParams struct {
	RelationshipType string
	Description      pgtype.Text
	ID               pgtype.UUID
}

func (q *Queries) UpdateFactionRelationship(ctx context.Context, arg UpdateFactionRelationshipParams) (FactionRelationship, error) {
	row := q.db.QueryRow(ctx, updateFactionRelationship, arg.RelationshipType, arg.Description, arg.ID)
	var i FactionRelationship
	err := row.Scan(
		&i.ID,
		&i.FactionID,
		&i.RelatedFactionID,
		&i.RelationshipType,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
