// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: items.sql

package statedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createItem = `-- name: CreateItem :one
INSERT INTO items (
  campaign_id,
  player_character_id,
  name,
  description,
  item_type,
  rarity,
  properties,
  equipped,
  quantity
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  COALESCE($7::jsonb, '{}'::jsonb),
  $8,
  $9
)
RETURNING id, campaign_id, player_character_id, name, description, item_type, rarity, properties, equipped, quantity, created_at, updated_at
`

type CreateItemParams struct {
	CampaignID        pgtype.UUID
	PlayerCharacterID pgtype.UUID
	Name              string
	Description       pgtype.Text
	ItemType          string
	Rarity            string
	Properties        []byte
	Equipped          bool
	Quantity          int32
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, createItem,
		arg.CampaignID,
		arg.PlayerCharacterID,
		arg.Name,
		arg.Description,
		arg.ItemType,
		arg.Rarity,
		arg.Properties,
		arg.Equipped,
		arg.Quantity,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.PlayerCharacterID,
		&i.Name,
		&i.Description,
		&i.ItemType,
		&i.Rarity,
		&i.Properties,
		&i.Equipped,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteItem = `-- name: DeleteItem :exec
DELETE FROM items
WHERE id = $1
`

func (q *Queries) DeleteItem(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteItem, id)
	return err
}

const getItemByID = `-- name: GetItemByID :one
SELECT id, campaign_id, player_character_id, name, description, item_type, rarity, properties, equipped, quantity, created_at, updated_at
FROM items
WHERE id = $1
`

func (q *Queries) GetItemByID(ctx context.Context, id pgtype.UUID) (Item, error) {
	row := q.db.QueryRow(ctx, getItemByID, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.PlayerCharacterID,
		&i.Name,
		&i.Description,
		&i.ItemType,
		&i.Rarity,
		&i.Properties,
		&i.Equipped,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listItemsByPlayer = `-- name: ListItemsByPlayer :many
SELECT id, campaign_id, player_character_id, name, description, item_type, rarity, properties, equipped, quantity, created_at, updated_at
FROM items
WHERE campaign_id = $1
  AND player_character_id IS NOT DISTINCT FROM $2
ORDER BY created_at, id
`

type ListItemsByPlayerParams struct {
	CampaignID        pgtype.UUID
	PlayerCharacterID pgtype.UUID
}

func (q *Queries) ListItemsByPlayer(ctx context.Context, arg ListItemsByPlayerParams) ([]Item, error) {
	rows, err := q.db.Query(ctx, listItemsByPlayer, arg.CampaignID, arg.PlayerCharacterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.PlayerCharacterID,
			&i.Name,
			&i.Description,
			&i.ItemType,
			&i.Rarity,
			&i.Properties,
			&i.Equipped,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemsByType = `-- name: ListItemsByType :many
SELECT id, campaign_id, player_character_id, name, description, item_type, rarity, properties, equipped, quantity, created_at, updated_at
FROM items
WHERE campaign_id = $1
  AND item_type = $2
ORDER BY created_at, id
`

type ListItemsByTypeParams struct {
	CampaignID pgtype.UUID
	ItemType   string
}

func (q *Queries) ListItemsByType(ctx context.Context, arg ListItemsByTypeParams) ([]Item, error) {
	rows, err := q.db.Query(ctx, listItemsByType, arg.CampaignID, arg.ItemType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.PlayerCharacterID,
			&i.Name,
			&i.Description,
			&i.ItemType,
			&i.Rarity,
			&i.Properties,
			&i.Equipped,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transferItem = `-- name: TransferItem :one
UPDATE items
SET
  player_character_id = $1,
  updated_at = now()
WHERE id = $2
RETURNING id, campaign_id, player_character_id, name, description, item_type, rarity, properties, equipped, quantity, created_at, updated_at
`

type TransferItemParams struct {
	PlayerCharacterID pgtype.UUID
	ID                pgtype.UUID
}

func (q *Queries) TransferItem(ctx context.Context, arg TransferItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, transferItem, arg.PlayerCharacterID, arg.ID)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.PlayerCharacterID,
		&i.Name,
		&i.Description,
		&i.ItemType,
		&i.Rarity,
		&i.Properties,
		&i.Equipped,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateItem = `-- name: UpdateItem :one
UPDATE items
SET
  name = $1,
  description = $2,
  item_type = $3,
  rarity = $4,
  properties = COALESCE($5::jsonb, properties),
  equipped = $6,
  quantity = $7,
  updated_at = now()
WHERE id = $8
RETURNING id, campaign_id, player_character_id, name, description, item_type, rarity, properties, equipped, quantity, created_at, updated_at
`

type UpdateItemParams struct {
	Name        string
	Description pgtype.Text
	ItemType    string
	Rarity      string
	Properties  []byte
	Equipped    bool
	Quantity    int32
	ID          pgtype.UUID
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, updateItem,
		arg.Name,
		arg.Description,
		arg.ItemType,
		arg.Rarity,
		arg.Properties,
		arg.Equipped,
		arg.Quantity,
		arg.ID,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.PlayerCharacterID,
		&i.Name,
		&i.Description,
		&i.ItemType,
		&i.Rarity,
		&i.Properties,
		&i.Equipped,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateItemEquipped = `-- name: UpdateItemEquipped :one
UPDATE items
SET
  equipped = $1,
  updated_at = now()
WHERE id = $2
RETURNING id, campaign_id, player_character_id, name, description, item_type, rarity, properties, equipped, quantity, created_at, updated_at
`

type UpdateItemEquippedParams struct {
	Equipped bool
	ID       pgtype.UUID
}

func (q *Queries) UpdateItemEquipped(ctx context.Context, arg UpdateItemEquippedParams) (Item, error) {
	row := q.db.QueryRow(ctx, updateItemEquipped, arg.Equipped, arg.ID)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.PlayerCharacterID,
		&i.Name,
		&i.Description,
		&i.ItemType,
		&i.Rarity,
		&i.Properties,
		&i.Equipped,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateItemQuantity = `-- name: UpdateItemQuantity :one
UPDATE items
SET
  quantity = $1,
  updated_at = now()
WHERE id = $2
RETURNING id, campaign_id, player_character_id, name, description, item_type, rarity, properties, equipped, quantity, created_at, updated_at
`

type UpdateItemQuantityParams struct {
	Quantity int32
	ID       pgtype.UUID
}

func (q *Queries) UpdateItemQuantity(ctx context.Context, arg UpdateItemQuantityParams) (Item, error) {
	row := q.db.QueryRow(ctx, updateItemQuantity, arg.Quantity, arg.ID)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.PlayerCharacterID,
		&i.Name,
		&i.Description,
		&i.ItemType,
		&i.Rarity,
		&i.Properties,
		&i.Equipped,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateItemProperties = `-- name: UpdateItemProperties :one
UPDATE items
SET
  properties = COALESCE($1::jsonb, properties),
  updated_at = now()
WHERE id = $2
RETURNING id, campaign_id, player_character_id, name, description, item_type, rarity, properties, equipped, quantity, created_at, updated_at
`

type UpdateItemPropertiesParams struct {
	Properties []byte
	ID         pgtype.UUID
}

func (q *Queries) UpdateItemProperties(ctx context.Context, arg UpdateItemPropertiesParams) (Item, error) {
	row := q.db.QueryRow(ctx, updateItemProperties, arg.Properties, arg.ID)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.PlayerCharacterID,
		&i.Name,
		&i.Description,
		&i.ItemType,
		&i.Rarity,
		&i.Properties,
		&i.Equipped,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
