// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: location_connections.sql

package statedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createConnection = `-- name: CreateConnection :one
INSERT INTO location_connections (
  from_location_id,
  to_location_id,
  description,
  bidirectional,
  travel_time,
  campaign_id
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
)
RETURNING id, from_location_id, to_location_id, description, bidirectional, travel_time, campaign_id
`

type CreateConnectionParams struct {
	FromLocationID pgtype.UUID
	ToLocationID   pgtype.UUID
	Description    pgtype.Text
	Bidirectional  bool
	TravelTime     pgtype.Text
	CampaignID     pgtype.UUID
}

func (q *Queries) CreateConnection(ctx context.Context, arg CreateConnectionParams) (LocationConnection, error) {
	row := q.db.QueryRow(ctx, createConnection,
		arg.FromLocationID,
		arg.ToLocationID,
		arg.Description,
		arg.Bidirectional,
		arg.TravelTime,
		arg.CampaignID,
	)
	var i LocationConnection
	err := row.Scan(
		&i.ID,
		&i.FromLocationID,
		&i.ToLocationID,
		&i.Description,
		&i.Bidirectional,
		&i.TravelTime,
		&i.CampaignID,
	)
	return i, err
}

const deleteConnection = `-- name: DeleteConnection :exec
DELETE FROM location_connections
WHERE id = $1
  AND campaign_id = $2
`

type DeleteConnectionParams struct {
	ID         pgtype.UUID
	CampaignID pgtype.UUID
}

func (q *Queries) DeleteConnection(ctx context.Context, arg DeleteConnectionParams) error {
	_, err := q.db.Exec(ctx, deleteConnection, arg.ID, arg.CampaignID)
	return err
}

const getConnectionsFromLocation = `-- name: GetConnectionsFromLocation :many
SELECT DISTINCT ON (connected_location_id)
  id, from_location_id, to_location_id, description, bidirectional, travel_time, campaign_id, connected_location_id, connected_location_name, connected_location_description
FROM (
  SELECT
    lc.id,
    lc.from_location_id,
    lc.to_location_id,
    lc.description,
    lc.bidirectional,
    lc.travel_time,
    lc.campaign_id,
    cl.id AS connected_location_id,
    cl.name AS connected_location_name,
    cl.description AS connected_location_description
  FROM location_connections lc
  JOIN locations cl ON cl.id = lc.to_location_id
  WHERE lc.campaign_id = $1
    AND lc.from_location_id = $2

  UNION ALL

  SELECT
    lc.id,
    -- Normalize row shape so returned edges are always from the requested location to the connected location.
    lc.to_location_id AS from_location_id,
    lc.from_location_id AS to_location_id,
    lc.description,
    lc.bidirectional,
    lc.travel_time,
    lc.campaign_id,
    cl.id AS connected_location_id,
    cl.name AS connected_location_name,
    cl.description AS connected_location_description
  FROM location_connections lc
  JOIN locations cl ON cl.id = lc.from_location_id
  WHERE lc.campaign_id = $1
    AND lc.to_location_id = $2
    AND lc.bidirectional = TRUE
) AS connections
ORDER BY connected_location_id, connected_location_name
`

type GetConnectionsFromLocationParams struct {
	CampaignID pgtype.UUID
	LocationID pgtype.UUID
}

type GetConnectionsFromLocationRow struct {
	ID                           pgtype.UUID
	FromLocationID               pgtype.UUID
	ToLocationID                 pgtype.UUID
	Description                  pgtype.Text
	Bidirectional                bool
	TravelTime                   pgtype.Text
	CampaignID                   pgtype.UUID
	ConnectedLocationID          pgtype.UUID
	ConnectedLocationName        string
	ConnectedLocationDescription pgtype.Text
}

func (q *Queries) GetConnectionsFromLocation(ctx context.Context, arg GetConnectionsFromLocationParams) ([]GetConnectionsFromLocationRow, error) {
	rows, err := q.db.Query(ctx, getConnectionsFromLocation, arg.CampaignID, arg.LocationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetConnectionsFromLocationRow
	for rows.Next() {
		var i GetConnectionsFromLocationRow
		if err := rows.Scan(
			&i.ID,
			&i.FromLocationID,
			&i.ToLocationID,
			&i.Description,
			&i.Bidirectional,
			&i.TravelTime,
			&i.CampaignID,
			&i.ConnectedLocationID,
			&i.ConnectedLocationName,
			&i.ConnectedLocationDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
