// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: locations.sql

package statedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLocation = `-- name: CreateLocation :one
INSERT INTO locations (
  campaign_id,
  name,
  description,
  region,
  location_type,
  properties
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  COALESCE($6::jsonb, '{}'::jsonb)
)
RETURNING id, campaign_id, name, description, region, location_type, properties, created_at, updated_at, player_visited, player_known
`

type CreateLocationParams struct {
	CampaignID   pgtype.UUID
	Name         string
	Description  pgtype.Text
	Region       pgtype.Text
	LocationType pgtype.Text
	Properties   []byte
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, createLocation,
		arg.CampaignID,
		arg.Name,
		arg.Description,
		arg.Region,
		arg.LocationType,
		arg.Properties,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Description,
		&i.Region,
		&i.LocationType,
		&i.Properties,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PlayerVisited,
		&i.PlayerKnown,
	)
	return i, err
}

const getLocationByID = `-- name: GetLocationByID :one
SELECT id, campaign_id, name, description, region, location_type, properties, created_at, updated_at, player_visited, player_known
FROM locations
WHERE id = $1
  AND ($2::uuid IS NULL OR campaign_id = $2)
`

type GetLocationByIDParams struct {
	ID         pgtype.UUID
	CampaignID pgtype.UUID
}

func (q *Queries) GetLocationByID(ctx context.Context, arg GetLocationByIDParams) (Location, error) {
	row := q.db.QueryRow(ctx, getLocationByID, arg.ID, arg.CampaignID)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Description,
		&i.Region,
		&i.LocationType,
		&i.Properties,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PlayerVisited,
		&i.PlayerKnown,
	)
	return i, err
}

const listLocationsByCampaign = `-- name: ListLocationsByCampaign :many
SELECT id, campaign_id, name, description, region, location_type, properties, created_at, updated_at, player_visited, player_known
FROM locations
WHERE campaign_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListLocationsByCampaign(ctx context.Context, campaignID pgtype.UUID) ([]Location, error) {
	rows, err := q.db.Query(ctx, listLocationsByCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Location
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Name,
			&i.Description,
			&i.Region,
			&i.LocationType,
			&i.Properties,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PlayerVisited,
			&i.PlayerKnown,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocationsByRegion = `-- name: ListLocationsByRegion :many
SELECT id, campaign_id, name, description, region, location_type, properties, created_at, updated_at, player_visited, player_known
FROM locations
WHERE campaign_id = $1
  AND region = $2
ORDER BY created_at, id
`

type ListLocationsByRegionParams struct {
	CampaignID pgtype.UUID
	Region     pgtype.Text
}

func (q *Queries) ListLocationsByRegion(ctx context.Context, arg ListLocationsByRegionParams) ([]Location, error) {
	rows, err := q.db.Query(ctx, listLocationsByRegion, arg.CampaignID, arg.Region)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Location
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Name,
			&i.Description,
			&i.Region,
			&i.LocationType,
			&i.Properties,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PlayerVisited,
			&i.PlayerKnown,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayerKnownLocations = `-- name: ListPlayerKnownLocations :many
SELECT id, campaign_id, name, description, region, location_type, properties, created_at, updated_at, player_visited, player_known
FROM locations
WHERE campaign_id = $1
  AND player_known = TRUE
ORDER BY created_at, id
`

func (q *Queries) ListPlayerKnownLocations(ctx context.Context, campaignID pgtype.UUID) ([]Location, error) {
	rows, err := q.db.Query(ctx, listPlayerKnownLocations, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Location
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Name,
			&i.Description,
			&i.Region,
			&i.LocationType,
			&i.Properties,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PlayerVisited,
			&i.PlayerKnown,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayerVisitedLocations = `-- name: ListPlayerVisitedLocations :many
SELECT id, campaign_id, name, description, region, location_type, properties, created_at, updated_at, player_visited, player_known
FROM locations
WHERE campaign_id = $1
  AND player_visited = TRUE
ORDER BY created_at, id
`

func (q *Queries) ListPlayerVisitedLocations(ctx context.Context, campaignID pgtype.UUID) ([]Location, error) {
	rows, err := q.db.Query(ctx, listPlayerVisitedLocations, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Location
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Name,
			&i.Description,
			&i.Region,
			&i.LocationType,
			&i.Properties,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PlayerVisited,
			&i.PlayerKnown,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setLocationPlayerKnown = `-- name: SetLocationPlayerKnown :exec
UPDATE locations
SET player_known = TRUE
WHERE id = $1
`

func (q *Queries) SetLocationPlayerKnown(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, setLocationPlayerKnown, id)
	return err
}

const setLocationPlayerVisited = `-- name: SetLocationPlayerVisited :exec
UPDATE locations
SET player_visited = TRUE
WHERE id = $1
`

func (q *Queries) SetLocationPlayerVisited(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, setLocationPlayerVisited, id)
	return err
}

const updateLocation = `-- name: UpdateLocation :one
UPDATE locations
SET
  name = $1,
  description = $2,
  region = $3,
  location_type = $4,
  properties = COALESCE($5::jsonb, '{}'::jsonb),
  updated_at = now()
WHERE id = $6
RETURNING id, campaign_id, name, description, region, location_type, properties, created_at, updated_at, player_visited, player_known
`

type UpdateLocationParams struct {
	Name         string
	Description  pgtype.Text
	Region       pgtype.Text
	LocationType pgtype.Text
	Properties   []byte
	ID           pgtype.UUID
}

func (q *Queries) UpdateLocation(ctx context.Context, arg UpdateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, updateLocation,
		arg.Name,
		arg.Description,
		arg.Region,
		arg.LocationType,
		arg.Properties,
		arg.ID,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Description,
		&i.Region,
		&i.LocationType,
		&i.Properties,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PlayerVisited,
		&i.PlayerKnown,
	)
	return i, err
}
