// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: memories.sql

package statedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	pgvector_go "github.com/pgvector/pgvector-go"
)

const createMemory = `-- name: CreateMemory :one
INSERT INTO memories (
  campaign_id,
  content,
  embedding,
  memory_type,
  location_id,
  npcs_involved,
  in_game_time,
  metadata
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  COALESCE($6::uuid[], '{}'::uuid[]),
  $7,
  COALESCE($8::jsonb, '{}'::jsonb)
)
RETURNING id, campaign_id, content, embedding, memory_type, location_id, npcs_involved, in_game_time, metadata, created_at
`

type CreateMemoryParams struct {
	CampaignID   pgtype.UUID
	Content      string
	Embedding    pgvector_go.Vector
	MemoryType   string
	LocationID   pgtype.UUID
	NpcsInvolved []pgtype.UUID
	InGameTime   pgtype.Text
	Metadata     []byte
}

func (q *Queries) CreateMemory(ctx context.Context, arg CreateMemoryParams) (Memory, error) {
	row := q.db.QueryRow(ctx, createMemory,
		arg.CampaignID,
		arg.Content,
		arg.Embedding,
		arg.MemoryType,
		arg.LocationID,
		arg.NpcsInvolved,
		arg.InGameTime,
		arg.Metadata,
	)
	var i Memory
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Content,
		&i.Embedding,
		&i.MemoryType,
		&i.LocationID,
		&i.NpcsInvolved,
		&i.InGameTime,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getMemoryByID = `-- name: GetMemoryByID :one
SELECT id, campaign_id, content, embedding, memory_type, location_id, npcs_involved, in_game_time, metadata, created_at
FROM memories
WHERE id = $1
`

func (q *Queries) GetMemoryByID(ctx context.Context, id pgtype.UUID) (Memory, error) {
	row := q.db.QueryRow(ctx, getMemoryByID, id)
	var i Memory
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Content,
		&i.Embedding,
		&i.MemoryType,
		&i.LocationID,
		&i.NpcsInvolved,
		&i.InGameTime,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listMemoriesByCampaign = `-- name: ListMemoriesByCampaign :many
SELECT id, campaign_id, content, embedding, memory_type, location_id, npcs_involved, in_game_time, metadata, created_at
FROM memories
WHERE campaign_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListMemoriesByCampaign(ctx context.Context, campaignID pgtype.UUID) ([]Memory, error) {
	rows, err := q.db.Query(ctx, listMemoriesByCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Memory
	for rows.Next() {
		var i Memory
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Content,
			&i.Embedding,
			&i.MemoryType,
			&i.LocationID,
			&i.NpcsInvolved,
			&i.InGameTime,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMemoriesBySimilarity = `-- name: SearchMemoriesBySimilarity :many
SELECT id, campaign_id, content, embedding, memory_type, location_id, npcs_involved, in_game_time, metadata, created_at,
       (embedding <=> $1::vector)::float8 AS distance
FROM memories
WHERE campaign_id = $2
ORDER BY embedding <=> $1::vector
LIMIT $3
`

type SearchMemoriesBySimilarityParams struct {
	QueryEmbedding pgvector_go.Vector
	CampaignID     pgtype.UUID
	LimitCount     int32
}

type SearchMemoriesBySimilarityRow struct {
	ID           pgtype.UUID
	CampaignID   pgtype.UUID
	Content      string
	Embedding    pgvector_go.Vector
	MemoryType   string
	LocationID   pgtype.UUID
	NpcsInvolved []pgtype.UUID
	InGameTime   pgtype.Text
	Metadata     []byte
	CreatedAt    pgtype.Timestamptz
	Distance     float64
}

func (q *Queries) SearchMemoriesBySimilarity(ctx context.Context, arg SearchMemoriesBySimilarityParams) ([]SearchMemoriesBySimilarityRow, error) {
	rows, err := q.db.Query(ctx, searchMemoriesBySimilarity, arg.QueryEmbedding, arg.CampaignID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchMemoriesBySimilarityRow
	for rows.Next() {
		var i SearchMemoriesBySimilarityRow
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Content,
			&i.Embedding,
			&i.MemoryType,
			&i.LocationID,
			&i.NpcsInvolved,
			&i.InGameTime,
			&i.Metadata,
			&i.CreatedAt,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMemoriesWithFilters = `-- name: SearchMemoriesWithFilters :many
SELECT id, campaign_id, content, embedding, memory_type, location_id, npcs_involved, in_game_time, metadata, created_at,
       (embedding <=> $1::vector)::float8 AS distance
FROM memories
WHERE campaign_id = $2
  AND ($3::text IS NULL OR memory_type = $3)
  AND ($4::uuid IS NULL OR location_id = $4)
  AND ($5::uuid IS NULL OR $5::uuid = ANY(npcs_involved))
  AND ($6::timestamptz IS NULL OR created_at >= $6)
  AND ($7::timestamptz IS NULL OR created_at <= $7)
ORDER BY embedding <=> $1::vector
LIMIT $8
`

type SearchMemoriesWithFiltersParams struct {
	QueryEmbedding pgvector_go.Vector
	CampaignID     pgtype.UUID
	MemoryType     pgtype.Text
	LocationID     pgtype.UUID
	NpcID          pgtype.UUID
	StartTime      pgtype.Timestamptz
	EndTime        pgtype.Timestamptz
	LimitCount     int32
}

type SearchMemoriesWithFiltersRow struct {
	ID           pgtype.UUID
	CampaignID   pgtype.UUID
	Content      string
	Embedding    pgvector_go.Vector
	MemoryType   string
	LocationID   pgtype.UUID
	NpcsInvolved []pgtype.UUID
	InGameTime   pgtype.Text
	Metadata     []byte
	CreatedAt    pgtype.Timestamptz
	Distance     float64
}

func (q *Queries) SearchMemoriesWithFilters(ctx context.Context, arg SearchMemoriesWithFiltersParams) ([]SearchMemoriesWithFiltersRow, error) {
	rows, err := q.db.Query(ctx, searchMemoriesWithFilters,
		arg.QueryEmbedding,
		arg.CampaignID,
		arg.MemoryType,
		arg.LocationID,
		arg.NpcID,
		arg.StartTime,
		arg.EndTime,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchMemoriesWithFiltersRow
	for rows.Next() {
		var i SearchMemoriesWithFiltersRow
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Content,
			&i.Embedding,
			&i.MemoryType,
			&i.LocationID,
			&i.NpcsInvolved,
			&i.InGameTime,
			&i.Metadata,
			&i.CreatedAt,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
