// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: npcs.sql

package statedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNPC = `-- name: CreateNPC :one
INSERT INTO npcs (
  campaign_id,
  name,
  description,
  personality,
  disposition,
  location_id,
  faction_id,
  alive,
  hp,
  stats,
  properties
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  COALESCE($10::jsonb, '{}'::jsonb),
  COALESCE($11::jsonb, '{}'::jsonb)
)
RETURNING id, campaign_id, name, description, personality, disposition, location_id, faction_id, alive, hp, stats, properties, created_at, updated_at
`

type CreateNPCParams struct {
	CampaignID  pgtype.UUID
	Name        string
	Description pgtype.Text
	Personality pgtype.Text
	Disposition int32
	LocationID  pgtype.UUID
	FactionID   pgtype.UUID
	Alive       bool
	Hp          pgtype.Int4
	Stats       []byte
	Properties  []byte
}

func (q *Queries) CreateNPC(ctx context.Context, arg CreateNPCParams) (Npc, error) {
	row := q.db.QueryRow(ctx, createNPC,
		arg.CampaignID,
		arg.Name,
		arg.Description,
		arg.Personality,
		arg.Disposition,
		arg.LocationID,
		arg.FactionID,
		arg.Alive,
		arg.Hp,
		arg.Stats,
		arg.Properties,
	)
	var i Npc
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Description,
		&i.Personality,
		&i.Disposition,
		&i.LocationID,
		&i.FactionID,
		&i.Alive,
		&i.Hp,
		&i.Stats,
		&i.Properties,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNPCByID = `-- name: GetNPCByID :one
SELECT id, campaign_id, name, description, personality, disposition, location_id, faction_id, alive, hp, stats, properties, created_at, updated_at
FROM npcs
WHERE id = $1
`

func (q *Queries) GetNPCByID(ctx context.Context, id pgtype.UUID) (Npc, error) {
	row := q.db.QueryRow(ctx, getNPCByID, id)
	var i Npc
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Description,
		&i.Personality,
		&i.Disposition,
		&i.LocationID,
		&i.FactionID,
		&i.Alive,
		&i.Hp,
		&i.Stats,
		&i.Properties,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const killNPC = `-- name: KillNPC :one
UPDATE npcs
SET
  alive = FALSE,
  updated_at = now()
WHERE id = $1
RETURNING id, campaign_id, name, description, personality, disposition, location_id, faction_id, alive, hp, stats, properties, created_at, updated_at
`

func (q *Queries) KillNPC(ctx context.Context, id pgtype.UUID) (Npc, error) {
	row := q.db.QueryRow(ctx, killNPC, id)
	var i Npc
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Description,
		&i.Personality,
		&i.Disposition,
		&i.LocationID,
		&i.FactionID,
		&i.Alive,
		&i.Hp,
		&i.Stats,
		&i.Properties,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAliveNPCsByLocation = `-- name: ListAliveNPCsByLocation :many
SELECT id, campaign_id, name, description, personality, disposition, location_id, faction_id, alive, hp, stats, properties, created_at, updated_at
FROM npcs
WHERE campaign_id = $1
  AND location_id = $2
  AND alive = TRUE
ORDER BY created_at, id
`

type ListAliveNPCsByLocationParams struct {
	CampaignID pgtype.UUID
	LocationID pgtype.UUID
}

func (q *Queries) ListAliveNPCsByLocation(ctx context.Context, arg ListAliveNPCsByLocationParams) ([]Npc, error) {
	rows, err := q.db.Query(ctx, listAliveNPCsByLocation, arg.CampaignID, arg.LocationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Npc
	for rows.Next() {
		var i Npc
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Name,
			&i.Description,
			&i.Personality,
			&i.Disposition,
			&i.LocationID,
			&i.FactionID,
			&i.Alive,
			&i.Hp,
			&i.Stats,
			&i.Properties,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNPCsByCampaign = `-- name: ListNPCsByCampaign :many
SELECT id, campaign_id, name, description, personality, disposition, location_id, faction_id, alive, hp, stats, properties, created_at, updated_at
FROM npcs
WHERE campaign_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListNPCsByCampaign(ctx context.Context, campaignID pgtype.UUID) ([]Npc, error) {
	rows, err := q.db.Query(ctx, listNPCsByCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Npc
	for rows.Next() {
		var i Npc
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Name,
			&i.Description,
			&i.Personality,
			&i.Disposition,
			&i.LocationID,
			&i.FactionID,
			&i.Alive,
			&i.Hp,
			&i.Stats,
			&i.Properties,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNPCsByFaction = `-- name: ListNPCsByFaction :many
SELECT id, campaign_id, name, description, personality, disposition, location_id, faction_id, alive, hp, stats, properties, created_at, updated_at
FROM npcs
WHERE campaign_id = $1
  AND faction_id = $2
ORDER BY created_at, id
`

type ListNPCsByFactionParams struct {
	CampaignID pgtype.UUID
	FactionID  pgtype.UUID
}

func (q *Queries) ListNPCsByFaction(ctx context.Context, arg ListNPCsByFactionParams) ([]Npc, error) {
	rows, err := q.db.Query(ctx, listNPCsByFaction, arg.CampaignID, arg.FactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Npc
	for rows.Next() {
		var i Npc
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Name,
			&i.Description,
			&i.Personality,
			&i.Disposition,
			&i.LocationID,
			&i.FactionID,
			&i.Alive,
			&i.Hp,
			&i.Stats,
			&i.Properties,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNPCsByLocation = `-- name: ListNPCsByLocation :many
SELECT id, campaign_id, name, description, personality, disposition, location_id, faction_id, alive, hp, stats, properties, created_at, updated_at
FROM npcs
WHERE campaign_id = $1
  AND location_id = $2
ORDER BY created_at, id
`

type ListNPCsByLocationParams struct {
	CampaignID pgtype.UUID
	LocationID pgtype.UUID
}

func (q *Queries) ListNPCsByLocation(ctx context.Context, arg ListNPCsByLocationParams) ([]Npc, error) {
	rows, err := q.db.Query(ctx, listNPCsByLocation, arg.CampaignID, arg.LocationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Npc
	for rows.Next() {
		var i Npc
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Name,
			&i.Description,
			&i.Personality,
			&i.Disposition,
			&i.LocationID,
			&i.FactionID,
			&i.Alive,
			&i.Hp,
			&i.Stats,
			&i.Properties,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNPC = `-- name: UpdateNPC :one
UPDATE npcs
SET
  name = $1,
  description = $2,
  personality = $3,
  disposition = $4,
  location_id = $5,
  faction_id = $6,
  alive = $7,
  hp = $8,
  stats = COALESCE($9::jsonb, '{}'::jsonb),
  properties = COALESCE($10::jsonb, '{}'::jsonb),
  updated_at = now()
WHERE id = $11
RETURNING id, campaign_id, name, description, personality, disposition, location_id, faction_id, alive, hp, stats, properties, created_at, updated_at
`

type UpdateNPCParams struct {
	Name        string
	Description pgtype.Text
	Personality pgtype.Text
	Disposition int32
	LocationID  pgtype.UUID
	FactionID   pgtype.UUID
	Alive       bool
	Hp          pgtype.Int4
	Stats       []byte
	Properties  []byte
	ID          pgtype.UUID
}

func (q *Queries) UpdateNPC(ctx context.Context, arg UpdateNPCParams) (Npc, error) {
	row := q.db.QueryRow(ctx, updateNPC,
		arg.Name,
		arg.Description,
		arg.Personality,
		arg.Disposition,
		arg.LocationID,
		arg.FactionID,
		arg.Alive,
		arg.Hp,
		arg.Stats,
		arg.Properties,
		arg.ID,
	)
	var i Npc
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Description,
		&i.Personality,
		&i.Disposition,
		&i.LocationID,
		&i.FactionID,
		&i.Alive,
		&i.Hp,
		&i.Stats,
		&i.Properties,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateNPCDisposition = `-- name: UpdateNPCDisposition :one
UPDATE npcs
SET
  disposition = $1,
  updated_at = now()
WHERE id = $2
RETURNING id, campaign_id, name, description, personality, disposition, location_id, faction_id, alive, hp, stats, properties, created_at, updated_at
`

type UpdateNPCDispositionParams struct {
	Disposition int32
	ID          pgtype.UUID
}

func (q *Queries) UpdateNPCDisposition(ctx context.Context, arg UpdateNPCDispositionParams) (Npc, error) {
	row := q.db.QueryRow(ctx, updateNPCDisposition, arg.Disposition, arg.ID)
	var i Npc
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Description,
		&i.Personality,
		&i.Disposition,
		&i.LocationID,
		&i.FactionID,
		&i.Alive,
		&i.Hp,
		&i.Stats,
		&i.Properties,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateNPCLocation = `-- name: UpdateNPCLocation :one
UPDATE npcs
SET
  location_id = $1,
  updated_at = now()
WHERE id = $2
RETURNING id, campaign_id, name, description, personality, disposition, location_id, faction_id, alive, hp, stats, properties, created_at, updated_at
`

type UpdateNPCLocationParams struct {
	LocationID pgtype.UUID
	ID         pgtype.UUID
}

func (q *Queries) UpdateNPCLocation(ctx context.Context, arg UpdateNPCLocationParams) (Npc, error) {
	row := q.db.QueryRow(ctx, updateNPCLocation, arg.LocationID, arg.ID)
	var i Npc
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Description,
		&i.Personality,
		&i.Disposition,
		&i.LocationID,
		&i.FactionID,
		&i.Alive,
		&i.Hp,
		&i.Stats,
		&i.Properties,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
