// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package statedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateCampaign(ctx context.Context, arg CreateCampaignParams) (Campaign, error)
	CreateConnection(ctx context.Context, arg CreateConnectionParams) (LocationConnection, error)
	CreateFaction(ctx context.Context, arg CreateFactionParams) (Faction, error)
	CreateFactionRelationship(ctx context.Context, arg CreateFactionRelationshipParams) (FactionRelationship, error)
	CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error)
	CreateNPC(ctx context.Context, arg CreateNPCParams) (Npc, error)
	CreatePlayerCharacter(ctx context.Context, arg CreatePlayerCharacterParams) (PlayerCharacter, error)
	CreateUser(ctx context.Context, name string) (User, error)
	DeleteCampaign(ctx context.Context, id pgtype.UUID) error
	DeleteConnection(ctx context.Context, arg DeleteConnectionParams) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	GetCampaignByID(ctx context.Context, id pgtype.UUID) (Campaign, error)
	GetConnectionsFromLocation(ctx context.Context, arg GetConnectionsFromLocationParams) ([]GetConnectionsFromLocationRow, error)
	GetFactionByID(ctx context.Context, id pgtype.UUID) (Faction, error)
	GetFactionRelationships(ctx context.Context, factionID pgtype.UUID) ([]FactionRelationship, error)
	GetLocationByID(ctx context.Context, id pgtype.UUID) (Location, error)
	GetNPCByID(ctx context.Context, id pgtype.UUID) (Npc, error)
	GetPlayerCharacterByCampaign(ctx context.Context, campaignID pgtype.UUID) ([]PlayerCharacter, error)
	GetPlayerCharacterByID(ctx context.Context, id pgtype.UUID) (PlayerCharacter, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByName(ctx context.Context, name string) (User, error)
	KillNPC(ctx context.Context, id pgtype.UUID) (Npc, error)
	ListAliveNPCsByLocation(ctx context.Context, arg ListAliveNPCsByLocationParams) ([]Npc, error)
	ListCampaignsByUser(ctx context.Context, createdBy pgtype.UUID) ([]Campaign, error)
	ListFactionsByCampaign(ctx context.Context, campaignID pgtype.UUID) ([]Faction, error)
	ListLocationsByCampaign(ctx context.Context, campaignID pgtype.UUID) ([]Location, error)
	ListLocationsByRegion(ctx context.Context, arg ListLocationsByRegionParams) ([]Location, error)
	ListNPCsByCampaign(ctx context.Context, campaignID pgtype.UUID) ([]Npc, error)
	ListNPCsByFaction(ctx context.Context, arg ListNPCsByFactionParams) ([]Npc, error)
	ListNPCsByLocation(ctx context.Context, arg ListNPCsByLocationParams) ([]Npc, error)
	ListUsers(ctx context.Context) ([]User, error)
	Ping(ctx context.Context) (int32, error)
	UpdateCampaign(ctx context.Context, arg UpdateCampaignParams) (Campaign, error)
	UpdateCampaignStatus(ctx context.Context, arg UpdateCampaignStatusParams) (Campaign, error)
	UpdateFaction(ctx context.Context, arg UpdateFactionParams) (Faction, error)
	UpdateFactionRelationship(ctx context.Context, arg UpdateFactionRelationshipParams) (FactionRelationship, error)
	UpdateLocation(ctx context.Context, arg UpdateLocationParams) (Location, error)
	UpdateNPC(ctx context.Context, arg UpdateNPCParams) (Npc, error)
	UpdateNPCDisposition(ctx context.Context, arg UpdateNPCDispositionParams) (Npc, error)
	UpdateNPCLocation(ctx context.Context, arg UpdateNPCLocationParams) (Npc, error)
	UpdatePlayerCharacter(ctx context.Context, arg UpdatePlayerCharacterParams) (PlayerCharacter, error)
	UpdatePlayerExperience(ctx context.Context, arg UpdatePlayerExperienceParams) (PlayerCharacter, error)
	UpdatePlayerHP(ctx context.Context, arg UpdatePlayerHPParams) (PlayerCharacter, error)
	UpdatePlayerLocation(ctx context.Context, arg UpdatePlayerLocationParams) (PlayerCharacter, error)
	UpdatePlayerStats(ctx context.Context, arg UpdatePlayerStatsParams) (PlayerCharacter, error)
	UpdatePlayerStatus(ctx context.Context, arg UpdatePlayerStatusParams) (PlayerCharacter, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
