// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: quests.sql

package statedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createQuest = `-- name: CreateQuest :one
INSERT INTO quests (
  campaign_id,
  parent_quest_id,
  title,
  description,
  quest_type,
  status
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
)
RETURNING id, campaign_id, parent_quest_id, title, description, quest_type, status, created_at, updated_at
`

type CreateQuestParams struct {
	CampaignID    pgtype.UUID
	ParentQuestID pgtype.UUID
	Title         string
	Description   pgtype.Text
	QuestType     string
	Status        string
}

func (q *Queries) CreateQuest(ctx context.Context, arg CreateQuestParams) (Quest, error) {
	row := q.db.QueryRow(ctx, createQuest,
		arg.CampaignID,
		arg.ParentQuestID,
		arg.Title,
		arg.Description,
		arg.QuestType,
		arg.Status,
	)
	var i Quest
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.ParentQuestID,
		&i.Title,
		&i.Description,
		&i.QuestType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQuestByID = `-- name: GetQuestByID :one
SELECT id, campaign_id, parent_quest_id, title, description, quest_type, status, created_at, updated_at
FROM quests
WHERE id = $1
`

func (q *Queries) GetQuestByID(ctx context.Context, id pgtype.UUID) (Quest, error) {
	row := q.db.QueryRow(ctx, getQuestByID, id)
	var i Quest
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.ParentQuestID,
		&i.Title,
		&i.Description,
		&i.QuestType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveQuests = `-- name: ListActiveQuests :many
SELECT id, campaign_id, parent_quest_id, title, description, quest_type, status, created_at, updated_at
FROM quests
WHERE campaign_id = $1
  AND status = 'active'
ORDER BY created_at, id
`

func (q *Queries) ListActiveQuests(ctx context.Context, campaignID pgtype.UUID) ([]Quest, error) {
	rows, err := q.db.Query(ctx, listActiveQuests, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Quest
	for rows.Next() {
		var i Quest
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.ParentQuestID,
			&i.Title,
			&i.Description,
			&i.QuestType,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestsByCampaign = `-- name: ListQuestsByCampaign :many
SELECT id, campaign_id, parent_quest_id, title, description, quest_type, status, created_at, updated_at
FROM quests
WHERE campaign_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListQuestsByCampaign(ctx context.Context, campaignID pgtype.UUID) ([]Quest, error) {
	rows, err := q.db.Query(ctx, listQuestsByCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Quest
	for rows.Next() {
		var i Quest
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.ParentQuestID,
			&i.Title,
			&i.Description,
			&i.QuestType,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestsByType = `-- name: ListQuestsByType :many
SELECT id, campaign_id, parent_quest_id, title, description, quest_type, status, created_at, updated_at
FROM quests
WHERE campaign_id = $1
  AND quest_type = $2
ORDER BY created_at, id
`

type ListQuestsByTypeParams struct {
	CampaignID pgtype.UUID
	QuestType  string
}

func (q *Queries) ListQuestsByType(ctx context.Context, arg ListQuestsByTypeParams) ([]Quest, error) {
	rows, err := q.db.Query(ctx, listQuestsByType, arg.CampaignID, arg.QuestType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Quest
	for rows.Next() {
		var i Quest
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.ParentQuestID,
			&i.Title,
			&i.Description,
			&i.QuestType,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubquestsByParentQuest = `-- name: ListSubquestsByParentQuest :many
SELECT id, campaign_id, parent_quest_id, title, description, quest_type, status, created_at, updated_at
FROM quests
WHERE parent_quest_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListSubquestsByParentQuest(ctx context.Context, parentQuestID pgtype.UUID) ([]Quest, error) {
	rows, err := q.db.Query(ctx, listSubquestsByParentQuest, parentQuestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Quest
	for rows.Next() {
		var i Quest
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.ParentQuestID,
			&i.Title,
			&i.Description,
			&i.QuestType,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQuest = `-- name: UpdateQuest :one
UPDATE quests
SET
  parent_quest_id = $1,
  title = $2,
  description = $3,
  quest_type = $4,
  status = $5,
  updated_at = now()
WHERE id = $6
RETURNING id, campaign_id, parent_quest_id, title, description, quest_type, status, created_at, updated_at
`

type UpdateQuestParams struct {
	ParentQuestID pgtype.UUID
	Title         string
	Description   pgtype.Text
	QuestType     string
	Status        string
	ID            pgtype.UUID
}

func (q *Queries) UpdateQuest(ctx context.Context, arg UpdateQuestParams) (Quest, error) {
	row := q.db.QueryRow(ctx, updateQuest,
		arg.ParentQuestID,
		arg.Title,
		arg.Description,
		arg.QuestType,
		arg.Status,
		arg.ID,
	)
	var i Quest
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.ParentQuestID,
		&i.Title,
		&i.Description,
		&i.QuestType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateQuestStatus = `-- name: UpdateQuestStatus :one
UPDATE quests
SET
  status = $1,
  updated_at = now()
WHERE id = $2
RETURNING id, campaign_id, parent_quest_id, title, description, quest_type, status, created_at, updated_at
`

type UpdateQuestStatusParams struct {
	Status string
	ID     pgtype.UUID
}

func (q *Queries) UpdateQuestStatus(ctx context.Context, arg UpdateQuestStatusParams) (Quest, error) {
	row := q.db.QueryRow(ctx, updateQuestStatus, arg.Status, arg.ID)
	var i Quest
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.ParentQuestID,
		&i.Title,
		&i.Description,
		&i.QuestType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
