// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: quest_objectives.sql

package statedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeObjective = `-- name: CompleteObjective :one
UPDATE quest_objectives
SET
  completed = TRUE
WHERE id = $1
RETURNING id, quest_id, description, completed, order_index
`

func (q *Queries) CompleteObjective(ctx context.Context, id pgtype.UUID) (QuestObjective, error) {
	row := q.db.QueryRow(ctx, completeObjective, id)
	var i QuestObjective
	err := row.Scan(
		&i.ID,
		&i.QuestID,
		&i.Description,
		&i.Completed,
		&i.OrderIndex,
	)
	return i, err
}

const createObjective = `-- name: CreateObjective :one
INSERT INTO quest_objectives (
  quest_id,
  description,
  completed,
  order_index
) VALUES (
  $1,
  $2,
  $3,
  $4
)
RETURNING id, quest_id, description, completed, order_index
`

type CreateObjectiveParams struct {
	QuestID     pgtype.UUID
	Description string
	Completed   bool
	OrderIndex  int32
}

func (q *Queries) CreateObjective(ctx context.Context, arg CreateObjectiveParams) (QuestObjective, error) {
	row := q.db.QueryRow(ctx, createObjective,
		arg.QuestID,
		arg.Description,
		arg.Completed,
		arg.OrderIndex,
	)
	var i QuestObjective
	err := row.Scan(
		&i.ID,
		&i.QuestID,
		&i.Description,
		&i.Completed,
		&i.OrderIndex,
	)
	return i, err
}

const listObjectivesByQuest = `-- name: ListObjectivesByQuest :many
SELECT id, quest_id, description, completed, order_index
FROM quest_objectives
WHERE quest_id = $1
ORDER BY order_index, id
`

func (q *Queries) ListObjectivesByQuest(ctx context.Context, questID pgtype.UUID) ([]QuestObjective, error) {
	rows, err := q.db.Query(ctx, listObjectivesByQuest, questID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuestObjective
	for rows.Next() {
		var i QuestObjective
		if err := rows.Scan(
			&i.ID,
			&i.QuestID,
			&i.Description,
			&i.Completed,
			&i.OrderIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateObjective = `-- name: UpdateObjective :one
UPDATE quest_objectives
SET
  description = $1,
  completed = $2,
  order_index = $3
WHERE id = $4
RETURNING id, quest_id, description, completed, order_index
`

type UpdateObjectiveParams struct {
	Description string
	Completed   bool
	OrderIndex  int32
	ID          pgtype.UUID
}

func (q *Queries) UpdateObjective(ctx context.Context, arg UpdateObjectiveParams) (QuestObjective, error) {
	row := q.db.QueryRow(ctx, updateObjective,
		arg.Description,
		arg.Completed,
		arg.OrderIndex,
		arg.ID,
	)
	var i QuestObjective
	err := row.Scan(
		&i.ID,
		&i.QuestID,
		&i.Description,
		&i.Completed,
		&i.OrderIndex,
	)
	return i, err
}
