// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: session_logs.sql

package statedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSessionLog = `-- name: CreateSessionLog :one
INSERT INTO session_logs (
  campaign_id,
  turn_number,
  player_input,
  input_type,
  llm_response,
  tool_calls,
  location_id,
  npcs_involved
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  COALESCE($6::jsonb, '[]'::jsonb),
  $7,
  COALESCE($8::uuid[], '{}'::uuid[])
)
RETURNING id, campaign_id, turn_number, player_input, input_type, llm_response, tool_calls, location_id, npcs_involved, created_at
`

type CreateSessionLogParams struct {
	CampaignID   pgtype.UUID
	TurnNumber   int32
	PlayerInput  string
	InputType    string
	LlmResponse  string
	ToolCalls    []byte
	LocationID   pgtype.UUID
	NpcsInvolved []pgtype.UUID
}

func (q *Queries) CreateSessionLog(ctx context.Context, arg CreateSessionLogParams) (SessionLog, error) {
	row := q.db.QueryRow(ctx, createSessionLog,
		arg.CampaignID,
		arg.TurnNumber,
		arg.PlayerInput,
		arg.InputType,
		arg.LlmResponse,
		arg.ToolCalls,
		arg.LocationID,
		arg.NpcsInvolved,
	)
	var i SessionLog
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.TurnNumber,
		&i.PlayerInput,
		&i.InputType,
		&i.LlmResponse,
		&i.ToolCalls,
		&i.LocationID,
		&i.NpcsInvolved,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionLogByID = `-- name: GetSessionLogByID :one
SELECT id, campaign_id, turn_number, player_input, input_type, llm_response, tool_calls, location_id, npcs_involved, created_at
FROM session_logs
WHERE id = $1
`

func (q *Queries) GetSessionLogByID(ctx context.Context, id pgtype.UUID) (SessionLog, error) {
	row := q.db.QueryRow(ctx, getSessionLogByID, id)
	var i SessionLog
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.TurnNumber,
		&i.PlayerInput,
		&i.InputType,
		&i.LlmResponse,
		&i.ToolCalls,
		&i.LocationID,
		&i.NpcsInvolved,
		&i.CreatedAt,
	)
	return i, err
}

const listRecentSessionLogs = `-- name: ListRecentSessionLogs :many
SELECT id, campaign_id, turn_number, player_input, input_type, llm_response, tool_calls, location_id, npcs_involved, created_at
FROM session_logs
WHERE campaign_id = $1
ORDER BY turn_number DESC, id DESC
LIMIT $2
`

type ListRecentSessionLogsParams struct {
	CampaignID pgtype.UUID
	LimitCount int32
}

func (q *Queries) ListRecentSessionLogs(ctx context.Context, arg ListRecentSessionLogsParams) ([]SessionLog, error) {
	rows, err := q.db.Query(ctx, listRecentSessionLogs, arg.CampaignID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionLog
	for rows.Next() {
		var i SessionLog
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.TurnNumber,
			&i.PlayerInput,
			&i.InputType,
			&i.LlmResponse,
			&i.ToolCalls,
			&i.LocationID,
			&i.NpcsInvolved,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionLogsByCampaign = `-- name: ListSessionLogsByCampaign :many
SELECT id, campaign_id, turn_number, player_input, input_type, llm_response, tool_calls, location_id, npcs_involved, created_at
FROM session_logs
WHERE campaign_id = $1
ORDER BY turn_number, id
`

func (q *Queries) ListSessionLogsByCampaign(ctx context.Context, campaignID pgtype.UUID) ([]SessionLog, error) {
	rows, err := q.db.Query(ctx, listSessionLogsByCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionLog
	for rows.Next() {
		var i SessionLog
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.TurnNumber,
			&i.PlayerInput,
			&i.InputType,
			&i.LlmResponse,
			&i.ToolCalls,
			&i.LocationID,
			&i.NpcsInvolved,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionLogsByLocation = `-- name: ListSessionLogsByLocation :many
SELECT id, campaign_id, turn_number, player_input, input_type, llm_response, tool_calls, location_id, npcs_involved, created_at
FROM session_logs
WHERE campaign_id = $1
  AND location_id = $2
ORDER BY turn_number, id
`

type ListSessionLogsByLocationParams struct {
	CampaignID pgtype.UUID
	LocationID pgtype.UUID
}

func (q *Queries) ListSessionLogsByLocation(ctx context.Context, arg ListSessionLogsByLocationParams) ([]SessionLog, error) {
	rows, err := q.db.Query(ctx, listSessionLogsByLocation, arg.CampaignID, arg.LocationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionLog
	for rows.Next() {
		var i SessionLog
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.TurnNumber,
			&i.PlayerInput,
			&i.InputType,
			&i.LlmResponse,
			&i.ToolCalls,
			&i.LocationID,
			&i.NpcsInvolved,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
