// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: world_facts.sql

package statedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFact = `-- name: CreateFact :one
INSERT INTO world_facts (
  campaign_id,
  fact,
  category,
  source
) VALUES (
  $1,
  $2,
  $3,
  $4
)
RETURNING id, campaign_id, fact, category, source, superseded_by, created_at
`

type CreateFactParams struct {
	CampaignID pgtype.UUID
	Fact       string
	Category   string
	Source     string
}

func (q *Queries) CreateFact(ctx context.Context, arg CreateFactParams) (WorldFact, error) {
	row := q.db.QueryRow(ctx, createFact,
		arg.CampaignID,
		arg.Fact,
		arg.Category,
		arg.Source,
	)
	var i WorldFact
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Fact,
		&i.Category,
		&i.Source,
		&i.SupersededBy,
		&i.CreatedAt,
	)
	return i, err
}

const getFactByID = `-- name: GetFactByID :one
SELECT id, campaign_id, fact, category, source, superseded_by, created_at
FROM world_facts
WHERE id = $1
`

func (q *Queries) GetFactByID(ctx context.Context, id pgtype.UUID) (WorldFact, error) {
	row := q.db.QueryRow(ctx, getFactByID, id)
	var i WorldFact
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Fact,
		&i.Category,
		&i.Source,
		&i.SupersededBy,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveFactsByCampaign = `-- name: ListActiveFactsByCampaign :many
SELECT id, campaign_id, fact, category, source, superseded_by, created_at
FROM world_facts
WHERE campaign_id = $1
  AND superseded_by IS NULL
ORDER BY created_at, id
`

func (q *Queries) ListActiveFactsByCampaign(ctx context.Context, campaignID pgtype.UUID) ([]WorldFact, error) {
	rows, err := q.db.Query(ctx, listActiveFactsByCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorldFact
	for rows.Next() {
		var i WorldFact
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Fact,
			&i.Category,
			&i.Source,
			&i.SupersededBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFactsByCampaign = `-- name: ListFactsByCampaign :many
SELECT id, campaign_id, fact, category, source, superseded_by, created_at
FROM world_facts
WHERE campaign_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListFactsByCampaign(ctx context.Context, campaignID pgtype.UUID) ([]WorldFact, error) {
	rows, err := q.db.Query(ctx, listFactsByCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorldFact
	for rows.Next() {
		var i WorldFact
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Fact,
			&i.Category,
			&i.Source,
			&i.SupersededBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFactsByCategory = `-- name: ListFactsByCategory :many
SELECT id, campaign_id, fact, category, source, superseded_by, created_at
FROM world_facts
WHERE campaign_id = $1
  AND category = $2
ORDER BY created_at, id
`

type ListFactsByCategoryParams struct {
	CampaignID pgtype.UUID
	Category   string
}

func (q *Queries) ListFactsByCategory(ctx context.Context, arg ListFactsByCategoryParams) ([]WorldFact, error) {
	rows, err := q.db.Query(ctx, listFactsByCategory, arg.CampaignID, arg.Category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorldFact
	for rows.Next() {
		var i WorldFact
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Fact,
			&i.Category,
			&i.Source,
			&i.SupersededBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const supersedeFact = `-- name: SupersedeFact :one
WITH previous_fact AS (
  SELECT world_facts.id, world_facts.campaign_id
  FROM world_facts
  WHERE world_facts.id = $1
),
new_fact AS (
  INSERT INTO world_facts (
    campaign_id,
    fact,
    category,
    source
  )
  SELECT
    campaign_id,
    $2,
    $3,
    $4
  FROM previous_fact
  RETURNING id, campaign_id, fact, category, source, superseded_by, created_at
),
updated_previous AS (
  UPDATE world_facts
  SET superseded_by = (SELECT id FROM new_fact)
  WHERE world_facts.id = (SELECT id FROM previous_fact)
  RETURNING id
)
SELECT
  new_fact.id,
  new_fact.campaign_id,
  new_fact.fact,
  new_fact.category,
  new_fact.source,
  new_fact.superseded_by,
  new_fact.created_at
FROM new_fact
JOIN updated_previous ON TRUE
`

type SupersedeFactParams struct {
	OldFactID pgtype.UUID
	Fact      string
	Category  string
	Source    string
}

type SupersedeFactRow struct {
	ID           pgtype.UUID
	CampaignID   pgtype.UUID
	Fact         string
	Category     string
	Source       string
	SupersededBy pgtype.UUID
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) SupersedeFact(ctx context.Context, arg SupersedeFactParams) (SupersedeFactRow, error) {
	row := q.db.QueryRow(ctx, supersedeFact,
		arg.OldFactID,
		arg.Fact,
		arg.Category,
		arg.Source,
	)
	var i SupersedeFactRow
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Fact,
		&i.Category,
		&i.Source,
		&i.SupersededBy,
		&i.CreatedAt,
	)
	return i, err
}
